# Generated by Django 2.0.5 on 2018-05-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-05-23 04:48:37+00:00'),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-05-23 04:48:37+00:00'),
        ),
    ]
