# Generated by Django 2.0.5 on 2018-07-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180619_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-06-29 07:12:33+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-06-29 07:12:33+00:00'),
        ),
    ]
