# Generated by Django 2.0.7 on 2018-07-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180709_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasourcemember',
            old_name='github_id',
            new_name='twitter_id',
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-07-19 19:58:35+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-07-19 19:58:35+00:00'),
        ),
    ]
