# Generated by Django 2.0.5 on 2018-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180530_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemember',
            name='access_token',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='github_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='scope',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datasourcemember',
            name='token_type',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-06-12 17:34:30+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-06-12 17:34:30+00:00'),
        ),
    ]
