# Generated by Django 2.0.5 on 2018-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180706_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcemember',
            name='token_expires',
            field=models.DateTimeField(default='2018-07-09 10:25:51+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_submitted',
            field=models.DateTimeField(default='2018-07-02 10:25:51+00:00'),
        ),
        migrations.AlterField(
            model_name='datasourcemember',
            name='last_updated',
            field=models.DateTimeField(default='2018-07-02 10:25:51+00:00'),
        ),
    ]
